### PR TITLE
Added resources for firewalld zone.

### PR DESCRIPTION
**Pull request by jkupferer**

### CODE REVIEW

**Comment by jhh** [comment]
I'm out on vacation this week and will look to get this merged this weekend.

**Comment by jkupferer** [comment]
I believe I still owe you unit tests for the new firewalld resources. I'm still coming up to speed on testing with chef... I ran all my code through simple tests on a vm at least. It looks like there should be at least a spec/unit/interface_spec.rb, spec/unit/service_spec, and a spec/unit/zone.rb.

**Comment by jkupferer** [comment]
Tests all pass now. I'm thinking now that the test/intergration/default/bats/default.bats should be split up into separate files for each resource like they are for rich_rules.

Also tests could be better. For example, using action :change on an interface our source associates it with one zone and removes it from any current zone... Tests don't check that yet.

**Comment by jhh** [comment]
It looks like the `.kitchen.yml` changes didn't get included in the pull request. Isolating the new features in their own suite is useful, something along the lines of:

``` yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - "recipe[fixture::port]"
      - "recipe[fixture::service]"
      - "recipe[fixture::rich_rule]"
      - "recipe[fixture::interface]"
      - "recipe[fixture::zone]"
      - "recipe[fixture::source]"
    attributes:

  - name: uic
    run_list:
      - "recipe[fixture::source]"
      - "recipe[fixture::interface]"
      - "recipe[fixture::zone]"
    attributes:

  - name: rich_rule
    run_list:
      - "recipe[fixture::rich_rule]"
    attributes:
```

**Comment by dgoradia** [comment]
Is this ready to merge? if so, can we?
If not, how can I help to move this forward?

**Comment by ryanjfrizzell** [comment]
bump anything else waiting on this merge? Was just about to work a PR that adds interface functionality.

**Pull request merged**
