### PR TITLE
Update rich_rule.rb

### PR DESCRIPTION
**Pull request by sspans**
remove 1/m limit value default

### CODE REVIEW

**Comment by swalberg** [comment]
:+1: I ran up against this today.

**Comment by jrpatterson** [comment]
I just hit this today as well. Could this patch be merged? 
Replacing my current rule with one that has a very high limit leaves the old rule in place as well.

```
    rule family="ipv4" source address="123.123.123.123/32" accept limit value="999/s"
    rule family="ipv4" source address="123.123.123.123/32" accept limit value="1/m"
```

**Comment by ghost** [comment]
Could this PR get integrated into master and the version bumped please?

I ran up against this the other day, having to specifically :remove rules with limit_value '1/m' to clean up, and add limit_value '1000/s' to stop firewalld from rate limiting connections.

Thanks!

**Comment by sspans** [comment]
Thanks!

**Pull request merged**
